default-subscription: &default-subscription
  url: https://api.v1.mk/sub?target=clash&exclude=官网|http|严禁|提示&url=订阅地址请用url编码
  # url: https://v.id9.cc/sub?target=clash&exclude=官网|http|严禁|提示&url=订阅地址请用url编码
  # url: https://sub.id9.cc/sub?target=clash&exclude=官网|http|严禁|提示&url=订阅地址请用url编码
  # url: https://sub.xeton.dev/sub?target=clash&exclude=官网|http|严禁|提示&url=订阅地址请用url编码
  # url: https://api.dler.io/sub?target=clash&exclude=官网|http|严禁|提示&url=订阅地址请用url编码
  # url: https://sub.maoxiongnet.com/sub?target=clash&exclude=官网|http|严禁|提示&url=订阅地址请用url编码

# 默认是需要有：香港、台湾、新加坡、日本、美国 这六个地区节点，如果其中一个国家没有，要修改本配置文件才能使用。
# 替换上面的“我是订阅链接”六个字为自己的订阅地址，多个用|号分开。
# exclude=后面是排除的正则匹配，比如那些官网地址的节点不想显示就是官网两个字匹配，需要自己增加，每个用|号分开。


# 本地HTTP(S)端口
# port: 7890

# 本地SOCKS5端口
# socks-port: 7891

# 透明代理端口Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# 透明代理端口Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S)和SOCKS5同一端口
mixed-port: 7890

# 允许LAN上的其他设备通过Clash访问Internet。
allow-lan: false

# 通过具有特定IP地址的lan访问
# "*": 绑定所有IP地址
# 192.168.122.11: 绑定单个IPv4地址
# "[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"

# 本地SOCKS5/HTTP（S）服务器的身份验证
# authentication: 
#   - "user1:password1"
#   - "user2:word2"

# Clash 模式选择
# global 全局模式
# rule   规则模式 (默认) 
# direct 直连模式
# script 脚本模式
mode: rule

# Clash核心的日志级别 
# Debug 将显示所有DNS查询和提供程序更新日志
# Debug 不会引起任何性能问题
# silent   静默
# error    错误
# warning  警告
# info     信息
# debug    调试
log-level: silent

# 外部控制器可以通过 RESTful API 从外部控制Clash
external-controller: 0.0.0.0:9090
# RESTful API的密码 (可选)
secret: '123456'

# 您可以将静态web资源(如clash dashboar)放到一个目录中,clash将在${API}/ui中提供服务
# 输入是配置目录的相对路径或绝对路径
# external-ui: folder

# 出站接口名称
# interface-name: eth0

# 不知道是什么意思反正是Linux上面的
# Provide a default mark for outbound connections under Linux.
# routing-mark: 6666

# 实验性选择
experimental:
# 将忽略dns解析失败,继续匹配规则,默认值为true
  ignore-resolve-fail: true

# 将在启动请求时连接到ipv6地址
# 默认值为false,它只建立到v4地址的连接。
ipv6: false

# 某些配置信息，部分功能仅适用于Premium内核
profile:
  # 时候存储的的选择节点信息
  # 如果有不同的配置文件有相同的组名，节点名，也会同步选择
  store-selected: true

  # 时候开启调试的API
  # 仅支持Premium内核
  # tracing: true

  # 时候持久化fake-ip
  # 从 v1.8.0 或者 Premium 2021.11.08开始支持
  store-fake-ip: true

# DNS服务器
dns:
  # 开启Clash内置DNS服务器
  # 默认为false
  enable: true
  # 不使用ipv6解析
  # 默认为false
  ipv6: false
  # DNS监听端口
  listen: 0.0.0.0:53
  # 解析nameserver和fallback的DNS服务器
  # 填入纯IP的DNS服务器
  default-nameserver:
    - 114.114.114.114
    - 180.76.76.76
    - 1.2.4.8
    - 8.8.8.8
    - 4.2.2.1
    - 4.2.2.2
  # 模式fake-ip  or  // 1.13.0内核，Premium 2023.01.29闭源内核移除 redir-host
  enhanced-mode: fake-ip
  # 使用本地hosts文件
  use-hosts: true
  # 国内用下列DNS解析
  nameserver:
    - udp://223.5.5.5
    - udp://180.76.76.76
    - udp://1.2.4.8
    - udp://210.2.4.8
    - tcp://114.114.114.114
    - tls://1.12.12.12
    - tls://120.53.53.53
    - tls://dns.alidns.com
    - tls://dot.pub
    - tls://dot.360.cn
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://doh.360.cn/dns-query
      # ipv6的DNS
    # - "[2400:3200::1]:53"
    # - "[2400:3200:baba::1]:53"
    # - https://2400:3200::1/dns-query
    # - https://2400:3200:baba::1/dns-query
    # - "[2402:4e00::]:53"
    # - "[2400:da00::6666]:53"
    # - "[2001:dc7:1000::1]:53"
    # - "[240C::6666]:53"
    # - "[240C::6644]:53"
    # - tls://dns.ipv6dns.com
    # - https://dns.ipv6dns.com/dns-query
    # - "[2001:cc0:2fff:1::6666]:53"
    # - "[2001:cc0:2fff:2::6]:53"
    # - "[2001:da8::666]:53"
    # - "[2001:da8:8000:1:202:120:2:101]:53"
    # - "[2001:da8:202:10::36]:53"
    # - "[2001:da8:202:10::37]:53"
    # - "[2001:da8:208:10::6]:53"
    # - "[2001:da8::666]:53"
  # 国外用下列DNS解析
  fallback:
    - tls://dns.google
    - tls://dns.adguard.com
    - tls://dns-family.adguard.com
    - tls://dot.sb
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - tls://one.one.one.one
    - https://dns.google/dns-query
    - https://dns.google/resolve
    - https://dns.quad9.net/dns-query
    - https://doh.opendns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.dns.sb/dns-query
    - https://doh.sb/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://doh-jp.blahdns.com/dns-query
    # 带家庭保护或者安全的DNS
    # - tls://dns.cleanbrowsing.org
    # - https://dns11.quad9.net/dns-query
    # - https://doh.familyshield.opendns.com/dns-query
    # - https://dns-family.adguard.com/dns-query
    # - https://doh.cleanbrowsing.org/doh/family-filter/
      # ipv6的DNS
    # - https://[2001:4860:4860::64]/dns-query
    # - https://[2001:4860:4860::6464]/dns-query
    # - https://[2606:4700:4700::1111]/dns-query
    # - https://[2606:4700:4700::1001]/dns-query
    # - https://[2606:4700:4700::64]/dns-query
    # - https://[2606:4700:4700::6464]/dns-query
    # - https://dns.quad9.net/dns-query
    # - https://dns11.quad9.net/dns-query
  # fake-ip仅有
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "+.*"
  # fake-ip仅有
  fallback-filter:
    # Meta内核配置，
      # getip: false
      # geosite: 
      #   - gfw
    # D大内核配置
    geoip: true
    geoip-code: CN
    # 通用配置
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.168.0.0/16
      - 192.88.99.0/24
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
  
# clash-for-android: 
  # 追加系统 DNS 到 nameserver 
  # append-system-dns: true 
  # ui-subtitle-pattern: "[\u4e00-\u9fa5]{2,4}"

# cfw 仅有
# 开启系统代理时将忽略这些域(或ip地址)
cfw-bypass:
  - "<local>"
  - 10.*
  - 127.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - localhost

# cfw仅有 
# 延迟测试设置
# 超时时间 单位秒
cfw-latency-timeout: 3000

# cfw仅有
# 测试网址
cfw-latency-url: http://cp.cloudflare.com/generate_204

# cfw仅有
# 更换节点 配置文件 模式 是否打断连接
# proxy   none(不切换) chain(连接中的代理组) all(全部)
# profile true(文件切换断开连接) false(不断开连接)
# mode    true(切换模式断开连接) false(不断开连接)
cfw-conn-break-strategy:
  proxy: all
  profile: true
  mode: true

# cfw仅有
# 排序规则
# default  默认
# latency  延迟
# alphabet 字母
cfw-proxies-order: default

proxy-providers:
  ALL-Node:
    type: http
    path: ./all/ALL-Node.yaml
    <<: *default-subscription
    interval: 10800
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 3600
  香港-Node:
    type: http
    path: ./all/香港-Node.yaml
    <<: *default-subscription
    interval: 10800
    filter: Hong|香港|HK
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 3600
  台湾-Node:
    type: http
    path: ./all/台湾-Node.yaml
    <<: *default-subscription
    interval: 10800
    filter: Taiwan|台湾|台北|新北|彰化|TW
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 3600
  新加坡-Node:
    type: http
    path: ./all/新加坡-Node.yaml
    <<: *default-subscription
    interval: 10800
    filter: Singapore|新加坡|狮城|SG
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 3600
  日本-Node:
    type: http
    path: ./all/日本-Node.yaml
    <<: *default-subscription
    interval: 10800
    filter: Japan|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 3600
  美国-Node:
    type: http
    path: ./all/美国-Node.yaml
    <<: *default-subscription
    interval: 10800
    filter: United States|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|LA
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 3600
  # 德国-Node:
  #   type: http
  #   path: ./all/德国-Node.yaml
  #   <<: *default-subscription
  #   interval: 10800
  #   filter: DE|德国
  #   health-check:
  #     enable: true
  #     url: https://cp.cloudflare.com/generate_204
  #     interval: 3600
  # 澳大利亚-Node:
  #   type: http
  #   path: ./all/澳大利亚-Node.yaml
  #   <<: *default-subscription
  #   interval: 10800
  #   filter: Oz|澳大利亚
  #   health-check:
  #     enable: true
  #     url: https://cp.cloudflare.com/generate_204
  #     interval: 3600

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Fallback
      - JP
      - TW
      - HK
      - SG
      - US
      # - DE
      # - Oz
    use:
      - ALL-Node
    url: http://cp.cloudflare.com/generate_204
    interval: 600
  - name: AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT
      - Proxy
    url: http://cp.cloudflare.com/generate_204
    interval: 600
  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - Proxy
    url: http://cp.cloudflare.com/generate_204
    interval: 600
  - name: Others
    type: select
    proxies:
      - Proxy
      - DIRECT
    url: http://cp.cloudflare.com/generate_204
    interval: 600
  - name: MainlandMedia
    type: select
    proxies:
      - Proxy
    url: http://cp.cloudflare.com/generate_204
    interval: 600
  - name: GlobalMedia
    type: select
    proxies:
      - Proxy
    url: http://cp.cloudflare.com/generate_204
    interval: 600
  - name: AppleAndMicrosoft
    type: select
    proxies:
      - DIRECT
      - Proxy
    url: http://cp.cloudflare.com/generate_204
    interval: 600
  - name: GameAndPayPal
    type: select
    proxies:
      - DIRECT
      - Proxy
    url: http://cp.cloudflare.com/generate_204
    interval: 600
  - name: SpeedTest
    type: select
    proxies:
      - DIRECT
      - Proxy
    url: http://cp.cloudflare.com/generate_204
    interval: 600
  - name: HK
    type: url-test
    use:
      - 香港-Node
    tolerance: 200
  - name: TW
    type: url-test
    use:
      - 台湾-Node
    tolerance: 200
  - name: SG
    type: url-test
    use:
      - 新加坡-Node
    tolerance: 200
  - name: JP
    type: url-test
    use:
      - 日本-Node
    tolerance: 200
  - name: US
    type: url-test
    use:
      - 美国-Node
    tolerance: 200
  # - name: DE
  #   type: url-test
  #   use:
  #     - 德国-Node
  #   tolerance: 200
  # - name: Oz
  #   type: url-test
  #   use:
  #     - 澳大利亚-Node
  #   tolerance: 200
  - name: Fallback
    type: fallback
    use:
      - ALL-Node
    tolerance: 150

rules:
  - RULE-SET,Reject,AdBlock
  # - GEOSITE,category-ads-all,AdBlock
  - RULE-SET,Direct,DIRECT

  - RULE-SET,Apple,AppleAndMicrosoft
  - RULE-SET,Microsoft,AppleAndMicrosoft
  - RULE-SET,PayPal,GameAndPayPal
  - RULE-SET,Game,GameAndPayPal
  
  - RULE-SET,GlobalMedia,GlobalMedia

  - RULE-SET,MainlandMedia,MainlandMedia

  - RULE-SET,PROXY,Proxy

  - RULE-SET,SpeedTest,SpeedTest
  - RULE-SET,Domestic,Domestic
  # - GEOSITE,geolocation-cn,Domestic
  # - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,CN,Domestic

  - MATCH,Others

rule-providers:
  Direct:
    behavior: classical
    interval: 86400
    path: ./Rules/Direct
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Direct.yaml'
  Domestic:
    behavior: classical
    interval: 86400
    path: ./Rules/Domestic
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Domestic.yaml'
  Game:
    behavior: classical
    interval: 86400
    path: ./Rules/Game
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Game.yaml'
  GlobalMedia:
    behavior: classical
    interval: 86400
    path: ./Rules/GlobalMedia
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/GlobalMedia.yaml'
  MainlandMedia:
    behavior: classical
    interval: 86400
    path: ./Rules/MainlandMedia
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/MainlandMedia.yaml'
  PROXY:
    behavior: classical
    interval: 86400
    path: ./Rules/Proxy
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Proxy.yaml'
  Reject:
    behavior: classical
    interval: 86400
    path: ./Rules/Reject
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Reject.yaml'
  Apple:
    behavior: classical
    interval: 86400
    path: ./Rules/Apple
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Apple.yaml'
  Microsoft:
    behavior: classical
    interval: 86400
    path: ./Rules/Microsoft
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/Microsoft.yaml'
  PayPal:
    behavior: classical
    interval: 86400
    path: ./Rules/PayPal
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/PayPal.yaml'
  SpeedTest:
    behavior: classical
    interval: 86400
    path: ./Rules/SpeedTest
    type: http
    url: 'https://endpoint.fastgit.org/https://github.com/zzcabc/Rules/blob/master/Rules_Provider/Integrate/SpeedTest.yaml'
  