# 本地HTTP(S)端口
# port: 7890

# 本地SOCKS5端口
# socks-port: 7891

# 透明代理端口Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# 透明代理端口Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S)和SOCKS5同一端口
mixed-port: 7890

# 允许LAN上的其他设备通过Clash访问Internet。
allow-lan: true

# 通过具有特定IP地址的lan访问
# "*": 绑定所有IP地址
# 192.168.122.11: 绑定单个IPv4地址
# "[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"

# 本地SOCKS5/HTTP（S）服务器的身份验证
# authentication: 
#   - "user1:password1"
#   - "user2:word2"

# Clash 模式选择
# global 全局模式
# rule   规则模式 (默认) 
# direct 直连模式
# script 脚本模式
mode: rule

# Clash核心的日志级别 
# Debug 将显示所有DNS查询和提供程序更新日志
# Debug 不会引起任何性能问题
# silent   静默
# error    错误
# warning  警告
# info     信息
# debug    调试
log-level: debug

# 外部控制器可以通过 RESTful API 从外部控制Clash
external-controller: 0.0.0.0:9090
# RESTful API的密码 (可选)
secret: '123456'

# 您可以将静态web资源(如clash dashboar)放到一个目录中,clash将在${API}/ui中提供服务
# 输入是配置目录的相对路径或绝对路径
# external-ui: folder

# 出站接口名称
# interface-name: eth0

# 实验性选择
experimental:
# 将忽略dns解析失败,继续匹配规则,默认值为true
  ignore-resolve-fail: true

# 将在启动请求时连接到ipv6地址
# 默认值为false,它只建立到v4地址的连接。
ipv6: false

# 开启系统代理时将忽略这些域(或ip地址)
cfw-bypass:
  - "<local>"
  - 10.*
  - 127.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - localhost

# 延迟测试设置
# 超时时间 单位秒
cfw-latency-timeout: 3000
# 测试网址
cfw-latency-url: http://www.gstatic.com/generate_204

# 更换节点 配置文件 模式 是否打断连接
# proxy   none(不切换) chain(连接中的代理组) all(全部)
# profile true(文件切换断开连接) false(不断开连接)
# mode    true(切换模式断开连接) false(不断开连接)
cfw-conn-break-strategy:
  proxy: all
  profile: true
  mode: true

# 排序规则
# default  默认
# latency  延迟
# alphabet 字母
cfw-proxies-order: default

# DNS服务器
dns:
  # 开启Clash内置DNS服务器
  # 默认为false
  enable: true
  # 不使用ipv6解析
  # 默认为false
  ipv6: false
  # DNS监听端口
  listen: 0.0.0.0:7874
  # 解析nameserver和fallback的DNS服务器
  # 填入纯IP的DNS服务器
  default-nameserver:
    - 114.114.114.114
    - 180.76.76.76
    - 8.8.8.8
  # 模式fake-ip  or  redir-host
  enhanced—mode: fake-ip
  # fake-ip 模式仅有
  fake-ip-range: 198.18.0.1/16
  # 使用本地hosts文件
  use-hosts: true
  # 国内用下列DNS解析
  nameserver:
    - 'tls://dns.alidns.com'
    - 'tls://doh.pub'
    - 'tls://dns.pub'
    - 'tls://dot.360.cn'
    - 'tls://dns.cfiec.net'
    - 'https://dns.alidns.com/dns-query'
    - 'https://doh.pub/dns-query'
    - 'https://dns.pub/dns-query'
    - 'https://doh.360.cn/dns-query'
    - 'https://dns.cfiec.net/dns-query'
    - 'https://rubyfish.cn/dns-query'
    - 'https://dns.rubyfish.cn/dns-quer'
  # 国内用下列DNS解析
  fallback:
    - 'tls://dns.google'
    - 'https://dns.google/dns-query'
    - 'https://dns.google/resolve'
    - 'https://dns.quad9.net/dns-query'
    - 'https://dns11.quad9.net/dns-query'
    - 'https://doh.opendns.com/dns-query'
    - 'https://doh.familyshield.opendns.com/dns-query'
    - 'https://cloudflare-dns.com/dns-query'
    - 'https://1.1.1.1/dns-query'
    - 'https://1.0.0.1/dns-query'
    - 'https://dns.adguard.com/dns-query'
    - 'https://dns-family.adguard.com/dns-query'
    - 'https://doh.dns.sb/dns-query'
    - 'https://doh.cleanbrowsing.org/doh/family-filter/'
    - 'https://doh.powerdns.org'
    - 'https://public.dns.iij.jp/dns-query'
    - 'https://doh-jp.blahdns.com/dns-query'
  # fake-ip仅有
  fake-ip-filter:
    - '*.126.net'
    - '*.kuwo.cn'
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - '*.music.163.com'
    - '*.music.migu.cn'
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - '*.time.edu.cn'
    - '*.xiami.com'
    - '*.y.qq.com'
    - '+.battlenet.com.cn'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.xboxlive.com'
    - 'stun.*.*.*'
    - 'stun.*.*'
    - "*.alibabacloud.com"
    - "*.alibabausercontent.com"
    - "*.alicdn.com"
    - "*.alicloudccp.com"
    - "*.aliexpress.com"
    - "*.aliimg.com"
    - "*.alikunlun.com"
    - "*.aliyun.com"
    - "*.aliyuncdn.com"
    - "*.aliyuncs.com"
    - "*.aliyundrive.com"
    - amobile.music.tc.qq.com
    - api-jooxtt.sanook.com
    - api.joox.com
    - aqqmusic.tc.qq.com
    - dl.stream.qqmusic.qq.com
    - heartbeat.belkin.com
    - isure.stream.qqmusic.qq.com
    - joox.com
    - localhost.ptlogin2.qq.com
    - mobileoc.music.tc.qq.com
    - music.163.com
    - music.migu.cn
    - music.taihe.com
    - musicapi.taihe.com
    - ntp.aliyun.com
    - ntp.ubuntu.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - pool.ntp.org
    - proxy.golang.org
    - songsearch.kugou.com
    - streamoc.music.tc.qq.com
    - time.apple.com
    - time.asia.apple.com
    - time.nist.gov
    - time.ustc.edu.cn
    - time.windows.com
    - time1.aliyun.com
    - time1.apple.com
    - time1.cloud.tencent.com
    - time1.google.com
    - time2.aliyun.com
    - time2.apple.com
    - time2.google.com
    - time3.aliyun.com
    - time3.apple.com
    - time3.google.com
    - time4.aliyun.com
    - time4.apple.com
    - time4.google.com
    - time5.aliyun.com
    - time5.apple.com
    - time6.aliyun.com
    - time6.apple.com
    - time7.aliyun.com
    - time7.apple.com
    - trackercdn.kugou.com
    - xbox.*.microsoft.com
    - y.qq.com
  # fake-ip仅有
  fallback-filter:
    geoip: false
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.168.0.0/16
      - 192.88.99.0/24
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.facebook.com'
      - '+.githubusercontent.com'
      - '+.google.com'
      - '+.youtube.com'
  
# clash-for-android: 
  # 追加系统 DNS 到 nameserver 
  # append-system-dns: true 
  # ui-subtitle-pattern: "[\u4e00-\u9fa5]{2,4}"